renewable_yield/config/routes.rb
Rails.application.routes.draw do

  resources :investments

  resources :providers

  resources :investors

  root 'welcome#home'

  get 'about' => 'about#about'

end

renewable_yield/app/models/provider.rb
class Provider < ActiveRecord::Base
end

renewable_yield/app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:company_name, :contact_first_name, :last_name, :company_phone_number, :company_street_address, :company_city, :company_state, :company_zip, :company_email, :password, :password_confirmation)
    end
end

renewable_yield/app/helpers/providers_helper.rb
module ProvidersHelper
end

renewable_yield/app/views/providers/_form.html.erb
<%= form_for(@provider, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @provider.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h4>

      <ul>
      <% @provider.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :contact_first_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :contact_first_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :last_name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_phone_number, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_phone_number, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_street_address, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_street_address, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_city, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_city, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_state, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_state, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_zip, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :company_zip, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :company_email, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :company_email, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :password, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :password_confirmation, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

renewable_yield/app/views/providers/edit.html.erb
<div class="page-header">
  <%= link_to providers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @provider, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing provider</h1>
</div>

<%= render 'form' %>

renewable_yield/app/views/providers/index.html.erb
<div class="page-header">
  <%= link_to new_provider_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Provider
  <% end %>
  <h1>Listing providers</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Company name</th>
            <th>Contact first name</th>
            <th>Last name</th>
            <th>Company phone number</th>
            <th>Company street address</th>
            <th>Company city</th>
            <th>Company state</th>
            <th>Company zip</th>
            <th>Company email</th>
            <th>Password</th>
            <th>Password confirmation</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @providers) do |provider| %>
            <td><%= provider.company_name %></td>
            <td><%= provider.contact_first_name %></td>
            <td><%= provider.last_name %></td>
            <td><%= provider.company_phone_number %></td>
            <td><%= provider.company_street_address %></td>
            <td><%= provider.company_city %></td>
            <td><%= provider.company_state %></td>
            <td><%= provider.company_zip %></td>
            <td><%= provider.company_email %></td>
            <td><%= provider.password %></td>
            <td><%= provider.password_confirmation %></td>
            <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Home', root_path %>
</div>

renewable_yield/app/views/providers/new.html.erb
<div class="page-header">
  <%= link_to providers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New provider</h1>
</div>

<%= render 'form' %>

renewable_yield/app/views/providers/show.html.erb
<div class="page-header">
  <%= link_to providers_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_provider_path(@provider), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show provider</h1>
</div>

<dl class="dl-horizontal">
  <dt>Company name:</dt>
  <dd><%= @provider.company_name %></dd>

  <dt>Contact first name:</dt>
  <dd><%= @provider.contact_first_name %></dd>

  <dt>Last name:</dt>
  <dd><%= @provider.last_name %></dd>

  <dt>Company phone number:</dt>
  <dd><%= @provider.company_phone_number %></dd>

  <dt>Company street address:</dt>
  <dd><%= @provider.company_street_address %></dd>

  <dt>Company city:</dt>
  <dd><%= @provider.company_city %></dd>

  <dt>Company state:</dt>
  <dd><%= @provider.company_state %></dd>

  <dt>Company zip:</dt>
  <dd><%= @provider.company_zip %></dd>

  <dt>Company email:</dt>
  <dd><%= @provider.company_email %></dd>

  <dt>Password:</dt>
  <dd><%= @provider.password %></dd>

  <dt>Password confirmation:</dt>
  <dd><%= @provider.password_confirmation %></dd>

</dl>