bottles_of_beer/config/routes.rb
Rails.application.routes.draw do
  get 'bottles_of_beer/:number_of_bottles' =>
    'drinking#bottles', as: 'bottles'

  get 'pass_one_around/:number_of_bottles' =>
    'drinking#pass', as: 'pass'
end

bottles_of_beer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bottles_of_beer/app/controllers/drinking_controller.rb
class DrinkingController < ApplicationController
  def bottles
    @bottles = params[:number_of_bottles].to_i

  end

  def pass
    @bottles = params[:number_of_bottles].to_i
    @bottles_less_one = @bottles - 1
    end
  end
end

bottles_of_beer/app/helpers/application_helper.rb
module ApplicationHelper
end

bottles_of_beer/app/views/drinking/bottles.html.erb
<p>
  <%= @bottles %> bottles of beer on the wall,
  <%= @bottles %> bottles of beer...
</p>

<%= link_to 'Take one down...', pass_path(number_of_bottles: @bottles) %>

bottles_of_beer/app/views/drinking/pass.html.erb
<p>
  <%= 'Pass it around, ' %>
  <%= @bottles_less_one %> bottles of beer on the wall.
</p>

<%= link_to 'Pass it around', bottles_path(number_of_bottles: @bottles_less_one) %>

bottles_of_beer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BottlesOfBeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>