renewable_yield/config/routes.rb
Rails.application.routes.draw do

  resources :investments

  resources :providers

  resources :investors

  root 'welcome#home'

  get 'about' => 'about#about'

end

renewable_yield/app/models/investment.rb
class Investment < ActiveRecord::Base
  def self.seed_investment!
    7.times do |number|
      @interest_rate = 1.50 + (0.50 * number)
      @maturity_date = number.years.from_now
      @issue_date = Date.today
      @offer_end_period = 3.months.from_now
      Investment.create(
      :term => number + 1,
      :interest_rate => @interest_rate,
      :minimum_order => 1_000,
      :denomination => 1_000,
      :maturity_date => @maturity_date,
      :issue_date => @issue_date,
      :offer_start_period => @issue_date,
      :offer_end_period => @offer_end_period
      )
    end
  end
end

renewable_yield/app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: [:show, :edit, :update, :destroy]

  # GET /investments
  # GET /investments.json
  def index
    @investments = Investment.all
  end

  # GET /investments/1
  # GET /investments/1.json
  def show
  end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit
  end

  # POST /investments
  # POST /investments.json
  def create
    @investment = Investment.new(investment_params)

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investment
      @investment = Investment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def investment_params
      params.require(:investment).permit(:term, :interest_rate, :minimum_order, :denomination, :maturity_date, :issue_date, :offer_start_period, :offer_end_period)
    end
end

renewable_yield/app/helpers/investments_helper.rb
module InvestmentsHelper
end

renewable_yield/app/views/investments/_form.html.erb
<%= form_for(@investment, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @investment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h4>

      <ul>
      <% @investment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :term, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :term, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :interest_rate, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :interest_rate, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :minimum_order, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :minimum_order, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :denomination, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :denomination, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :maturity_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :maturity_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :issue_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :issue_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :offer_start_period, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :offer_start_period, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :offer_end_period, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :offer_end_period, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

renewable_yield/app/views/investments/edit.html.erb
<div class="page-header">
  <%= link_to investments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @investment, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing investment</h1>
</div>

<%= render 'form' %>

renewable_yield/app/views/investments/index.html.erb
<div class="page-header">
  <%= link_to new_investment_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Investment
  <% end %>
  <h1>Listing investments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Term</th>
            <th>Interest rate</th>
            <th>Minimum order</th>
            <th>Denomination</th>
            <th>Maturity date</th>
            <th>Issue date</th>
            <th>Offer start period</th>
            <th>Offer end period</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @investments) do |investment| %>
            <td><%= investment.term %></td>
            <td><%= investment.interest_rate %></td>
            <td><%= investment.minimum_order %></td>
            <td><%= investment.denomination %></td>
            <td><%= investment.maturity_date %></td>
            <td><%= investment.issue_date %></td>
            <td><%= investment.offer_start_period %></td>
            <td><%= investment.offer_end_period %></td>
            <td><%= link_to 'Show', investment %></td>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
        <td><%= link_to 'Destroy', investment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Home', root_path %>
</div>

renewable_yield/app/views/investments/new.html.erb
<div class="page-header">
  <%= link_to investments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New investment</h1>
</div>

<%= render 'form' %>

renewable_yield/app/views/investments/show.html.erb
<div class="page-header">
  <%= link_to investments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_investment_path(@investment), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show investment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Term:</dt>
  <dd><%= @investment.term %></dd>

  <dt>Interest rate:</dt>
  <dd><%= @investment.interest_rate %></dd>

  <dt>Minimum order:</dt>
  <dd><%= @investment.minimum_order %></dd>

  <dt>Denomination:</dt>
  <dd><%= @investment.denomination %></dd>

  <dt>Maturity date:</dt>
  <dd><%= @investment.maturity_date %></dd>

  <dt>Issue date:</dt>
  <dd><%= @investment.issue_date %></dd>

  <dt>Offer start period:</dt>
  <dd><%= @investment.offer_start_period %></dd>

  <dt>Offer end period:</dt>
  <dd><%= @investment.offer_end_period %></dd>

</dl>